### ISSUE TITLE
Full page cache and customer data

### ISSUE THREAD

**Issue by mokadev** [lcs-prbnc/probance-magento2#8]
Hi,

in this file /view/frontend/templates/js/visit.phtml, you set the customer ID and email in the template code but this block is cached by FPC so the email and the customer ID si the same for every visitor...

You should get the customer informations stored in local storage with a javascript call

**Comment by sdkwebprojects** [comment]
Version 1.5.3 correct this using fetch to get dynamic data such as customer email (if logged in/out during site surfing) or current product id (if on a product page)
